sudo: false
language: node_js
node_js:
  - node
branches:
  only:
    - master
notifications:
  email: false
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run watch:build
  - npm test
